micronaut:
  application:
    name: Order Service
  server:
    port: 9090
orders:
  nike:
    id: 1
    product: Nike
    quantity: 2
    price: 242.50
  adidas:
    id: 2
    product: Adidas
    quantity: 3
    price: 320.75